dist: xenial

language: scala

jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

branches:
  only:
    - source

before_install:
  - wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
  - if [ "$( sha256sum wkhtmltox_0.12.5-1.xenial_amd64.deb | awk '{ print $1}' )" != "df203cee4dc9b3efb8d0cd6fc25fa819883224f50c75b76bd9c856903711dc14" ]; then echo wkhtmltox checksum incorrect; exit 1; fi
  - sudo apt-get install gdebi-core
  - sudo gdebi --n wkhtmltox_0.12.5-1.xenial_amd64.deb

script:
  - sbt clean hepek

after_script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - cd target/web/public/main/site/
  - wkhtmltopdf --print-media-type --zoom 1.33 --viewport-size 1280x1024 --margin-left 0 --margin-right 0 resume.html cv.pdf
  - cp ../../../../../.travis.yml .
  - git init
  - git add -A
  - git commit -a -m "Site build from Travis ($TRAVIS_BUILD_NUMBER) at $(date -u)"
  - git remote add origin https://${GH_TOKEN}@${REMOTE}
  - git push -f origin master:master | grep -v http

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete